### ISSUE TITLE
r50 net

### ISSUE THREAD

**Issue by Amanda-Barbara** [lcings/opencv_retinaface#1]
I only detected 2 faces on your demo.jpg when I use Charrin/RetinaFace-Cpp r50.caffemodel, what I need to modify? thanks!

**Comment by lcings** [comment]
Mat blob_input = dnn::blobFromImage(img, 1.0, blob_size, cv::Scalar(127, 127, 127), true, false, CV_32FC1);
changge to:
Mat blob_input = dnn::blobFromImage(img, 1.0, blob_size, cv::Scalar(0, 0, 0), true, false, CV_32FC1);

**Comment by Amanda-Barbara** [comment]
I will have a try, Thanks.
